# Generated by Django 5.2 on 2025-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elonlar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
