# Generated by Django 5.2 on 2025-12-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Elonlar',
            },
        ),
        migrations.CreateModel(
            name='Haqimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('title_uz', models.CharField(null=True)),
                ('title_en', models.CharField(null=True)),
                ('title_ru', models.CharField(null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Biz haqimizda',
            },
        ),
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familya', models.CharField()),
                ('ism_familya_uz', models.CharField(null=True)),
                ('ism_familya_en', models.CharField(null=True)),
                ('ism_familya_ru', models.CharField(null=True)),
                ('sohasi', models.CharField(max_length=100)),
                ('sohasi_uz', models.CharField(max_length=100, null=True)),
                ('sohasi_en', models.CharField(max_length=100, null=True)),
                ('sohasi_ru', models.CharField(max_length=100, null=True)),
                ('mutaxassis', models.TextField()),
                ('mutaxassis_uz', models.TextField(null=True)),
                ('mutaxassis_en', models.TextField(null=True)),
                ('mutaxassis_ru', models.TextField(null=True)),
                ('haqida', models.TextField()),
                ('haqida_uz', models.TextField(null=True)),
                ('haqida_en', models.TextField(null=True)),
                ('haqida_ru', models.TextField(null=True)),
                ('yutuqlar', models.TextField()),
                ('yutuqlar_uz', models.TextField(null=True)),
                ('yutuqlar_en', models.TextField(null=True)),
                ('yutuqlar_ru', models.TextField(null=True)),
                ('maqsadlarim', models.TextField()),
                ('maqsadlarim_uz', models.TextField(null=True)),
                ('maqsadlarim_en', models.TextField(null=True)),
                ('maqsadlarim_ru', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='rahbariyat/')),
            ],
            options={
                'verbose_name_plural': 'Rahbariyat',
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Yunalishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=20, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=20, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=20, null=True, verbose_name='Title')),
                ('description', models.TextField(max_length=150, verbose_name='Description')),
                ('description_uz', models.TextField(max_length=150, null=True, verbose_name='Description')),
                ('description_en', models.TextField(max_length=150, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(max_length=150, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='yunalishlar/')),
                ('kurs', models.CharField(choices=[('9-SINF', '9-SINF'), ('11-SINF', '11-SINF')], default={'9-SINF': '9-SINF'}, verbose_name='Kurs UZ')),
                ('kurs_ru', models.CharField(choices=[('9-Х КЛАССОВ', '9-Х КЛАССОВ'), ('11-Х КЛАССОВ', '11-Х КЛАССОВ')], default={'9-Х КЛАССОВ': '9-Х КЛАССОВ'}, verbose_name='Kurs RU')),
                ('kurs_en', models.CharField(choices=[('9TH GRADE', '9TH GRADE'), ('11TH GRADE', '11TH GRADE')], default={'9TH GRADE': '9TH GRADE'}, verbose_name='Kurs EN')),
                ('shakl', models.CharField(choices=[('KUNDUZGI', 'KUNDUZGI'), ('DUAL', 'DUAL')], default={'KUNDUZGI': 'KUNDUZGI'}, verbose_name='Shakl UZ')),
                ('shakl_ru', models.CharField(choices=[('ОЧНУЮ', 'ОЧНУЮ'), ('ДУАЛЬНУЮ', 'ДУАЛЬНУЮ')], default={'ОЧНУЮ': 'ОЧНУЮ'}, verbose_name='Shakl RU')),
                ('shakl_en', models.CharField(choices=[('DAYTIME', 'DAYTIME'), ('DUAL', 'DUAL')], default={'DAYTIME': 'DAYTIME'}, verbose_name='Shakl EN')),
            ],
            options={
                'verbose_name_plural': 'Yunalishlar',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleries/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('elonlar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='mainapp.elonlar')),
                ('haqimizda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='mainapp.haqimizda')),
                ('yangiliklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='mainapp.yangiliklar')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
    ]
